basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: hector.gonzalez@bunsan.io
    name: Héctor González
    url: http://github.com/hectorgool/ocr
  description: This is a sample Lector OCR server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Lector OCR API
  version: "1.0"
paths:
  /logs:
    get:
      description: Get a json with, id, Endpoint, Method, Input, Output, CreatedOn,
        stored in log_db of database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Get a json with the fields in the table log_db of database
      tags:
      - bunsan
  /numbers:
    post:
      consumes:
      - application/json
      description: Send data to the server to proces the numbers of the OCR, the list
        of numbers must be code in base64 for proces
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: send data to the server to proces the numbers of the OCR
      tags:
      - bunsan
swagger: "2.0"
